name: piececalc
version: 1.0.0+10
publish_to: none
description: Piecework calculator
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  bloc: ^9.0.0
  cross_file: ^0.3.3+5
  currency_picker: ^2.0.16
  equatable: ^2.0.5
  file_picker: ^10.2.0
  firebase_core: ^3.15.1
  firebase_core_web: ^2.8.0
  firebase_crashlytics: ^4.3.9
  firebase_performance: ^0.10.1+9
  fl_chart: ^1.0.0
  flex_color_picker: ^3.3.0
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_typeahead: ^5.2.0
  get_it: ^8.0.3
  google_fonts: ^6.0.0
  intl: any
  introduction_screen: ^3.1.11
  logging: ^1.2.0
  package_info_plus: ^8.3.0
  path: ^1.8.3
  path_provider: ^2.1.0
  pubspec_dependency_sorter: ^1.0.4
  share_plus: ^11.0.0
  shared_preferences: ^2.2.0
  sqflite: ^2.2.8+4
  sqflite_common_ffi: any
  sqflite_common_ffi_web: ^1.0.0
  universal_html: ^2.2.4
  url_launcher: ^6.0.10
  uuid: ^4.0.0

dev_dependencies: 
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^9.0.0
flutter:
  assets:
    - assets/launcher_icon.png
    - assets/web_icon/launcher_icon.png
    - assets/chart.png
    - assets/intro/intro_second_screen.png
    - assets/intro/intro_third_page.png
    - assets/intro/intro_fourth_page.png
    - assets/intro/intro_theme_change.png
    - assets/intro/intro_fifth_page.png
    - assets/intro/intro_seventh_page.png
    - assets/google_fonts/
    - assets/empty_archive.png
  uses-material-design: true
  generate: true
flutter_intl: 
  enabled: true
