name: piececalc
version: 1.0.0+1
publish_to: none
description: Piecework calculator
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  bloc: ^8.1.2
  currency_picker: ^2.0.16
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_typeahead: ^4.6.2
  get_it: ^7.6.0
  google_fonts: ^5.1.0
  intl: ^0.18.0
  logging: ^1.2.0
  path: ^1.8.3
  path_provider: ^2.1.0
  pubspec_dependency_sorter: ^1.0.4
  share: ^2.0.4
  shared_preferences: ^2.2.0
  sqflite: ^2.2.8+4
  uuid: ^3.0.7

dev_dependencies: 
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0
flutter: 
  uses-material-design: true
  generate: true
flutter_intl: 
  enabled: true
