name: piececalc
version: 1.0.0+1
publish_to: none
description: Piecework calculator
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  bloc: ^8.1.2
  cross_file: ^0.3.3+5
  currency_picker: ^2.0.16
  equatable: ^2.0.5
  firebase_core: ^2.15.1
  firebase_core_web: ^2.8.0
  firebase_crashlytics: ^3.3.5
  firebase_performance: ^0.9.2+5
  fl_chart: ^0.63.0
  flex_color_picker: ^3.3.0
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_typeahead: ^4.6.2
  get_it: ^7.6.0
  google_fonts: ^6.0.0
  intl: ^0.18.0
  introduction_screen: ^3.1.11
  logging: ^1.2.0
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.0
  pubspec_dependency_sorter: ^1.0.4
  share_plus: ^4.5.3
  shared_preferences: ^2.2.0
  sqflite: ^2.2.8+4
  sqflite_common_ffi: any
  sqflite_common_ffi_web: ^0.4.0
  url_launcher: ^6.0.10
  uuid: ^4.0.0

dev_dependencies: 
  bloc_test: ^9.1.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0
flutter:
  assets:
    - assets/launcher_icon.png
    - assets/chart.png
    - assets/intro/intro_second_screen.png
    - assets/intro/intro_third_page.png
    - assets/intro/intro_fourth_page.png
    - assets/intro/intro_theme_change.png
    - assets/intro/intro_fifth_page.png
    - assets/intro/intro_seventh_page.png
    - assets/google_fonts/
    - assets/empty_archive.png
  uses-material-design: true
  generate: true
flutter_intl: 
  enabled: true
